### ISSUE TITLE
Always see this when I start

### ISSUE THREAD

**Issue by roger-tbg** [Code-Forge-Net/Remix-Forge#18]
<img width="576" alt="CleanShot 2023-11-01 at 09 56 01@2x" src="https://github.com/Code-Forge-Net/Remix-Forge/assets/141795220/7230661e-35e2-45c5-b21b-8054ef7d6390">

Nothing bad going on -- just thought i'd file the issue in case either: "Everyone sees this and that can be made known, or I have a unique situation"

**Comment by AlemTuzlak** [comment]
@roger-tbg hmm I've never seen this happen, do you have npm installed?

**Comment by roger-tbg** [comment]
> @roger-tbg hmm I've never seen this happen, do you have npm installed?

Yep.  Node v18.17.1, npm v9.6.7

Both should be available to vscode (start it from my shell)

**Comment by AlemTuzlak** [comment]
@roger-tbg found the culprit, fixed in 0.5.1
