### ISSUE TITLE
Should be monorepo aware

### ISSUE THREAD

**Issue by bradymwilliams** [Code-Forge-Net/Remix-Forge#3]
When using forge actions via right click - only the files specifically prompted get placed correctly.

## Example:

Init shadcn-ui in your template via package.json in `apps/your-remix-app/package.json` the tailwind.config.js file gets created at the monorepo root rather than remaining contextually aware of where `package.json` lived.

**Comment by AlemTuzlak** [comment]
Interesting, will look into fixing this, I knowwhat the cause us
